// generated 2000/1/6 21:43:29 EET by exa@orion.(none)
// using glademm V0.5.5
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/exa/devel/promptspace/promptspace-gui/promptspace-gui.glade
// for gtk 1.2.6 and gtkmm 1.0.3
//
// Please modify the corresponding derived classes in src/app1.cc

#include "app1.hh"
#include <libgnomeui/gnome-stock.h>

App1_Glade::App1_Glade(
) : Gnome_App("app1", ""), new_file1(new_file1_gtkpmmi), open1(open1_gtkpmmi), save1(save1_gtkpmmi), save_as1(save_as1_gtkpmmi), exit1(exit1_gtkpmmi), cut1(cut1_gtkpmmi), copy1(copy1_gtkpmmi), paste1(paste1_gtkpmmi), clear1(clear1_gtkpmmi), properties1(properties1_gtkpmmi), preferences1(preferences1_gtkpmmi), about1(about1_gtkpmmi)
{   toolbar1 = new Gtk_Toolbar(GTK_ORIENTATION_HORIZONTAL, GTK_TOOLBAR_BOTH);
   new_file1.set_name("new_file1");
   connect_to_method(new_file1.activate, (App1*)this, &App1::on_new_file1_activate);
   open1.set_name("open1");
   connect_to_method(open1.activate, (App1*)this, &App1::on_open1_activate);
   save1.set_name("save1");
   connect_to_method(save1.activate, (App1*)this, &App1::on_save1_activate);
   save_as1.set_name("save_as1");
   connect_to_method(save_as1.activate, (App1*)this, &App1::on_save_as1_activate);
   separator1.set_name("separator1");
   exit1.set_name("exit1");
   connect_to_method(exit1.activate, (App1*)this, &App1::on_exit1_activate);
   file1_menu.set_name("file1_menu");
   file1_menu.append(new_file1);
   file1_menu.append(open1);
   file1_menu.append(save1);
   file1_menu.append(save_as1);
   file1_menu.append(separator1);
   file1_menu.append(exit1);
   file1.set_name("file1");
   file1.set_submenu(file1_menu);
   cut1.set_name("cut1");
   connect_to_method(cut1.activate, (App1*)this, &App1::on_cut1_activate);
   copy1.set_name("copy1");
   connect_to_method(copy1.activate, (App1*)this, &App1::on_copy1_activate);
   paste1.set_name("paste1");
   connect_to_method(paste1.activate, (App1*)this, &App1::on_paste1_activate);
   clear1.set_name("clear1");
   connect_to_method(clear1.activate, (App1*)this, &App1::on_clear1_activate);
   separator2.set_name("separator2");
   properties1.set_name("properties1");
   connect_to_method(properties1.activate, (App1*)this, &App1::on_properties1_activate);
   edit1_menu.set_name("edit1_menu");
   edit1_menu.append(cut1);
   edit1_menu.append(copy1);
   edit1_menu.append(paste1);
   edit1_menu.append(clear1);
   edit1_menu.append(separator2);
   edit1_menu.append(properties1);
   edit1.set_name("edit1");
   edit1.set_submenu(edit1_menu);
   view1_menu.set_name("view1_menu");
   view1.set_name("view1");
   view1.set_submenu(view1_menu);
   preferences1.set_name("preferences1");
   connect_to_method(preferences1.activate, (App1*)this, &App1::on_preferences1_activate);
   settings1_menu.set_name("settings1_menu");
   settings1_menu.append(preferences1);
   settings1.set_name("settings1");
   settings1.set_submenu(settings1_menu);
   about1.set_name("about1");
   connect_to_method(about1.activate, (App1*)this, &App1::on_about1_activate);
   help1_menu.set_name("help1_menu");
   help1_menu.append(about1);
   help1.set_name("help1");
   help1.set_submenu(help1_menu);
   menubar1.set_name("menubar1");
   menubar1.append(file1);
   menubar1.append(edit1);
   menubar1.append(view1);
   menubar1.append(settings1);
   menubar1.append(help1);
   dockitem1.set_name("dockitem1");
   toolbar1->set_name("toolbar1");
   toolbar1->set_border_width(1);
   toolbar1->set_space_size(16);
   toolbar1->set_tooltips(true);
   toolbar1->set_button_relief(GTK_RELIEF_NONE);
   toolbar1->set_space_style(GTK_TOOLBAR_SPACE_LINE);
   button1 = new Gtk_Button(GTK_BUTTON(gtk_toolbar_append_element(GTK_TOOLBAR(toolbar1->gtkobj()), GTK_TOOLBAR_CHILD_BUTTON, 0, "New", 0, 0, GTK_WIDGET(gnome_stock_pixmap_widget(GTK_WIDGET(toolbar1->gtkobj()), GNOME_STOCK_PIXMAP_NEW)), 0, 0)));
   button2 = new Gtk_Button(GTK_BUTTON(gtk_toolbar_append_element(GTK_TOOLBAR(toolbar1->gtkobj()), GTK_TOOLBAR_CHILD_BUTTON, 0, "Open", 0, 0, GTK_WIDGET(gnome_stock_pixmap_widget(GTK_WIDGET(toolbar1->gtkobj()), GNOME_STOCK_PIXMAP_OPEN)), 0, 0)));
   button3 = new Gtk_Button(GTK_BUTTON(gtk_toolbar_append_element(GTK_TOOLBAR(toolbar1->gtkobj()), GTK_TOOLBAR_CHILD_BUTTON, 0, "Save", 0, 0, GTK_WIDGET(gnome_stock_pixmap_widget(GTK_WIDGET(toolbar1->gtkobj()), GNOME_STOCK_PIXMAP_SAVE)), 0, 0)));
   button1->set_name("button1");
   _tooltips.set_tip(*button1, "New File", "");
   button2->set_name("button2");
   _tooltips.set_tip(*button2, "Open File", "");
   button3->set_name("button3");
   _tooltips.set_tip(*button3, "Save File", "");
   dockitem2.set_name("dockitem2");
   hbox1.set_name("hbox1");
   dock1.set_name("dock1");
   appbar1.set_name("appbar1");
   set_name("app1");
   set_title("Promptspace-gui");
   add(&dock1);
   add(&appbar1);
   new_file1.show();
   open1.show();
   save1.show();
   save_as1.show();
   separator1.show();
   exit1.show();
   file1_menu.show();
   file1.show();
   cut1.show();
   copy1.show();
   paste1.show();
   clear1.show();
   separator2.show();
   properties1.show();
   edit1_menu.show();
   edit1.show();
   view1_menu.show();
   view1.show();
   preferences1.show();
   settings1_menu.show();
   settings1.show();
   about1.show();
   help1_menu.show();
   help1.show();
   menubar1.show();
   dockitem1.show();
   button1->show();
   button2->show();
   button3->show();
   toolbar1->show();
   dockitem2.show();
   hbox1.show();
   dock1.show();
   appbar1.show();
   show();
}

App1_Glade::~App1_Glade()
{   delete button1;
   delete button2;
   delete button3;
   delete toolbar1;
}
