# generated 2000/1/6 21:43:29 EET by exa@orion.(none)
# using glademm V0.5.5
#
# newer (non customized) versions of this file go to Makefile_glade
# this file will overwrite itself !

all:
	./autogen.sh
